# Generated by Django 5.0 on 2023-12-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_list', '0002_chat_message'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER enforce_unique_chat_users
                BEFORE INSERT ON chat_list_chat
                BEGIN
                    SELECT RAISE(ABORT, 'User1 and User2 must be different')
                    WHERE NEW.user1_id = NEW.user2_id;
                END;
                """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS enforce_unique_chat_users;
                """
        ),
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX unique_chat_users
                ON chat_list_chat (user1_id, user2_id);
                """,
            reverse_sql="""
                DROP INDEX IF EXISTS unique_chat_users;
                """
        ),
    ]
