# Generated by Django 5.0 on 2023-12-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_list', '0003_auto_20231224_0328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatList',
        ),
    ]
